name: 合并去重规则

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 触发 (对应日本时间早上 9:00)
  workflow_dispatch: # 手动触发工作流的选项

jobs:
  merge_rules:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装所需 Python 库
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 定义规则 URL
        id: get_urls
        run: |
          # 读取 rule/Direct/Direct.txt 文件中的 ruleset URL
          rule_urls=$(cat $GITHUB_WORKSPACE/rule/Direct/Direct.txt)
          # 将多行 URL 用空格连接成一行，并通过输出传递给下一步
          echo "rule_urls=$(echo "$rule_urls" | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
      - name: 设置 RULE_URLS 环境变量
        env:
          RULE_URLS: ${{ steps.get_urls.outputs.rule_urls }}

      - name: 下载并合并规则
        run: |
          mkdir -p merged_rules
          rule_urls=$(echo "$RULE_URLS" | tr '\n' ' ')
          IFS=' ' read -ra URL_ARRAY <<< "$rule_urls"
          download_success=true
          for url in "${URL_ARRAY[@]}"; do
            filename=$(basename "$url")
            echo "正在下载 $url 到 merged_rules/$filename..."
            if curl -sSL --connect-timeout 10 --max-time 30 "$url" -o "merged_rules/$filename"; then
              echo "成功下载 $url"
            else
              echo "下载 $url 失败"
              download_success=false
            fi
          done
          if [ "$download_success" = true ]; then
            echo "所有规则下载成功。正在合并文件..."
            cat merged_rules/* > merged_rules/merged.txt
          else
            echo "错误: 并非所有规则都下载成功。跳过合并。"
            exit 1
          fi

      - name: 去重规则
        run: |
          if [ -f "merged_rules/merged.txt" ]; then
            echo "正在去重规则..."
            sort -u merged_rules/merged.txt -o merged_rules/deduplicated.txt
          else
            echo "错误: merged_rules/merged.txt 文件未找到。跳过去重。"
            exit 1
          fi

      - name: 保存去重后的规则到单个文件
        run: |
          if [ -f "merged_rules/deduplicated.txt" ]; then
            echo "正在保存去重后的规则到 combined_rules.list..."
            cat merged_rules/deduplicated.txt > combined_rules.list
          else
            echo "错误: merged_rules/deduplicated.txt 文件未找到。跳过保存。"
            exit 1
          fi

      - name: 从 Direct/Direct.txt 生成直连规则
        run: |
          python generate_direct_rules.py Direct/Direct.txt direct_rules.yaml

      - name: 提交并推送更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动化规则更新 (合并去重并生成直连规则)"
          file_pattern: combined_rules.list direct_rules.yaml
